In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [8]:
X = np.random.randint(8 , size = (17 , 6))

In [53]:
X

array([[4, 6, 5, 4, 6, 0],
       [5, 3, 2, 4, 5, 3],
       [7, 2, 1, 4, 1, 4],
       [6, 7, 3, 4, 7, 0],
       [7, 2, 5, 0, 1, 4],
       [0, 6, 1, 5, 0, 3],
       [4, 6, 6, 2, 0, 3],
       [1, 6, 6, 3, 2, 0],
       [5, 7, 4, 0, 7, 5],
       [7, 4, 2, 6, 3, 7],
       [1, 6, 3, 5, 7, 2],
       [1, 1, 0, 5, 0, 4],
       [7, 6, 4, 6, 3, 6],
       [0, 1, 0, 7, 3, 1],
       [2, 1, 5, 5, 2, 1],
       [6, 0, 3, 6, 2, 7],
       [4, 1, 2, 5, 5, 1]])

In [10]:
y = np.random.randint(7 , size = (17 , 1))

In [54]:
y

array([[4],
       [3],
       [2],
       [5],
       [0],
       [5],
       [6],
       [1],
       [5],
       [4],
       [6],
       [3],
       [2],
       [3],
       [4],
       [3],
       [5]])

In [95]:
def updation(weights ,bias , X , y):
    loss = 0.0
    cost = 0.0
    tcost = 0.0
    for i in range(len(X)):
        ypred = np.dot(weights , X[i])
        ypred += bias
        loss += (ypred - y[i]) ** 2
        tcost += (ypred - y[i])
    cost = loss / (2 * (len(X)))
    tcost /= len(X)
    return cost , tcost

In [149]:
def iterations(X , y , alpha = 0.00001):
    weights = np.random.uniform(low = min(X[0]) , high = max(X[0]) , size = (4 , ) )
    bias = 0
    temp = 0
    for i in range(250):
        cost , tcost  = updation(weights , bias , X , y)
        for i in range(len(X[0])):
            weights[i] = weights[i] - alpha * tcost * weights[i]
            bias = bias - alpha * tcost
        if (abs(temp - cost) < 1e-5):
            break
        temp = cost
    return cost

In [150]:
iterations(X , y)

3418948.664283343

In [69]:
df = pd.read_csv("employee_data.csv")

In [71]:
df.drop(['groups'] , axis = 1 , inplace = True)

In [83]:
df

Unnamed: 0   id  age  healthy_eating  active_lifestyle  salary
0             0    0   36               5                 5    2297
1             1    1   55               3                 5    1134
2             2    2   61               8                 1    4969
3             3    3   29               3                 6     902
4             4    4   34               6                 2    3574
..          ...  ...  ...             ...               ...     ...
995         995  995   33               7                 7    2996
996         996  996   21               1                 2     667
997         997  997   49               9                 7    4158
998         998  998   56               6                 7    2414
999         999  999   64               4                 9     788

[1000 rows x 6 columns]

In [73]:
cols = df.columns

In [74]:
cols = cols[ 1: ] 

In [79]:
y = df[cols[-1]]

In [84]:
X = df[cols[ : -1]]

In [86]:
X = X.to_numpy()

In [89]:
y = y.to_numpy()

In [98]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [99]:
X = sc.fit_transform(X)

In [124]:
from sklearn.linear_model import LinearRegression as LR

In [136]:
lr = LR()

In [138]:
pred = lr.fit(X , y)

In [133]:
y_pred = lr.predict(X)

In [134]:
cost = 0
for i in range(len(y_pred)):
    cost += (y_pred[i] - y[i]) ** 2
cost /= 2 * len(X)

In [135]:
cost

81575.82983549795

In [139]:
pred.coef_

array([   2.3372577 ,   -7.82088614,  938.63603674, -377.93508318])

In [142]:
iterations(X , y)

array([ -160.65560115,  -420.17886964, -1197.60284858,   -81.49187858])